### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by grafiktr** [facebookmicrosites/fbmentorship#16]
Hello, I make a living by translating articles, lectures and some other documents. I saw that you’ve downloaded a project to GitHub. I would like to help you by translating it to Turkish. If you would like to work with me, could you please give me a permission for translation? Thank you in advanced

**Comment by caabernathy** [comment]
Feel free to send a pull request for what you're looking to do. If you're familiar with [Docusaurus](https://docusaurus.io/) which this website is built with, you should be able to get this up and running.
