### ISSUE TITLE
Greetings from Divyanshu

### ISSUE THREAD

**Issue by divyanshu-rawat** [facebookmicrosites/fbmentorship#54]
I have applied for FB open-source Mentorship program but didn't hear anything from the facebook till so fat.
It's been 1 month since I applied.
kindly let me know is there any way to know the status of the application.
Best
Divyanshu

**Comment by divyanshu-rawat** [comment]
@caabernathy can you let me know the status?

**Comment by yangshun** [comment]
I'm not sure either. Perhaps you could try again in future.
